### ISSUE TITLE
RoofClassify - TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by BnJ24** [DINFO-UniFI/RoofClassify#54]
### What is the bug or the crash?

Bonjour
J'essaie donc de "jouer" pour la première fois avec le plugin en indiquant comme :
- dossier hébergeant le raster à classifier un dossier dans lequel j'ai collé mon raster "pansharpé"/"découpé",
- dossier hébergeant les shapefiles d'entrainement un dossier contenant mes quatres shapes (zinc, concreto etc.),
- raster d'entrainement le même raster "pansharpé"/"découpé",
- dossier de sortie, un dossier vide "output".
J'obtiens de type d'erreur :
"TypeError: 'NoneType' object is not callable Traceback (most recent call last):
  File "C:\Users/Benjamin LYSANIUK/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RoofClassify\plugin_main.py", line 273, in run
    classifier = DataClassifier()
TypeError: 'NoneType' object is not callable"

### Steps to reproduce the issue

![issue3](https://user-images.githubusercontent.com/85962418/149157838-ad08f8f9-0c6b-487a-9bea-a692fb2fe14e.JPG)
![issue1](https://user-images.githubusercontent.com/85962418/149157843-b1fb9b62-c45a-4a2c-979b-814d6b2190d9.JPG)
![issue2](https://user-images.githubusercontent.com/85962418/149157845-53ebdca2-0a10-4f14-a5e6-4c3f815fbbc5.JPG)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.16.15-Hannover | Révision du code | e7fdad64
-- | -- | -- | --
Compilé avec Qt | 5.15.2 | Utilisant Qt | 5.15.2
Compilé avec GDAL/OGR | 3.4.0 | Utilisé avec GDAL/OGR | 3.4.0
Compilé avec GEOS | 3.10.0-CAPI-1.16.0 | Utilisé avec GEOS | 3.10.0-CAPI-1.16.0
Compilé avec SQLite | 3.35.2 | Fonctionne avec SQLite | 3.35.2
Version du client PostgreSQL | 13.0 | Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.11.5
Compilé avec PROJ | 8.2.0 | Fonctionne avec PROJ | Rel. 8.2.0, November 1st, 2021
Version de l'OS | Windows 10 Version 2009
Extensions Python actives | db_manager; MetaSearch; processing; RoofClassify

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Guts** [comment]
Merci @BnJ24 d'avoir pris soin de créer un ticket.

Une nouvelle version vient d'être publiée :
- https://github.com/DINFO-UniFI/RoofClassify/releases/tag/1.0.0-beta3
- https://plugins.qgis.org/plugins/RoofClassify/version/1.0.0-beta3/

Mais j'ai identifié 2 problèmes :
- il y a une différence entre le zip généré par GitHub Actions et déposé sur GitHub Release (premier lien au-dessu) et celui envoyé sur plugins.qgis.org (2ème lien ci-dessus)
- il y a un souci dans le packaging car, pour fonctionner sous Windows, scikit-learn génère ses propres dépendances binaires (des sortes de dll : https://docs.python.org/3/faq/windows.html#is-a-pyd-file-the-same-as-a-dll) et qui par défaut ne sont pas incluses dans le zip. Donc faut qu'on creuse de ce côté là. Peut-être devrons-nous abandonner l'idée d'un déploiement complètement automatisé...

En attendant, je dépose une version manuellement que tu devrais pouvoir tester.

**Comment by Guts** [comment]
J'ai demandé de l'aide aux autres contributeurs de qgis-plugin-ci : https://github.com/opengisch/qgis-plugin-ci/issues/106
