### ISSUE TITLE
Switch from QGIS 2 to QGIS 3

### ISSUE THREAD

**Issue by Guts** [DINFO-UniFI/RoofClassify#9]
To upgrade:

* Python 3.x
* PyQt 5
* PyQGIS 3.x

Here comes the list of future QGIS skills which will be interesting for the plugin:

* [Plugin migration to QGIS 3](https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3)

**Comment by quythytruong** [comment]
As PR #13 makes it possible to open the plugin in QGIS 3, I suppose we can close this issue ? :)
